### ISSUE TITLE
how to compile  Sample Source Code

### ISSUE THREAD

**Issue by suzixin** [paulmckrcu/perfbook#1]
Just entering `perfbook/CodeSamples` and `make`？
There's  lots of error.

![截图](https://user-images.githubusercontent.com/21327882/68524391-54284f80-0301-11ea-9b47-3cd61f624d13.PNG)

**Comment by paulmckrcu** [comment]
On Fri, Nov 08, 2019 at 10:58:11PM -0800, suzixin wrote:
> Just entering `perfbook/CodeSamples` and `make`？
> There's  lots of error.
> 
> ![截图](https://user-images.githubusercontent.com/21327882/68524391-54284f80-0301-11ea-9b47-3cd61f624d13.PNG)

Thank you for trying this out!

You are building on 64-bit ARMv8, correct?

I don't have access to that hardware, but given the error messages, one
thing to try is to remove the "-mcpu=native -mtune=native" from the
file "CodeSamples/arch-arm64/Makefile.arch".

If that does not work, ignore the comment in "CodeSamples/Makefile.arch"
and make the change there.  (If you have to do this, some Makefile
dependencies might need adjusting.)

Does any of that help?

And of course I would welcome patches that fix things on ARMv8!

								Thanx, Paul

**Comment by paulmckrcu** [comment]
Given no follow-up in several months, I am closing this issue.

It is quite possible that recent changes to ARMv8 portions of the build system have fixed this.
