### ISSUE TITLE
[whymb] Missing writeback

### ISSUE THREAD

**Issue by kalaider** [paulmckrcu/perfbook#4]
Before CPU0 can mark its cache line as "shared", the line must be written back to main memory to prevent data loss. It is worth mentioning here as long as we are concerned with main memory at all.

https://github.com/paulmckrcu/perfbook/blob/1dd2b89ab3e7bb64a380d7ccef7033757dd442ef/appendix/whymb/whymemorybarriers.tex#L792-L796

https://github.com/paulmckrcu/perfbook/blob/1dd2b89ab3e7bb64a380d7ccef7033757dd442ef/appendix/whymb/whymemorybarriers.tex#L892-L898

**Comment by paulmckrcu** [comment]
Good point, thank you!

This is addressed by commit e68dcb9a4f1a ("appendix/whymb: Add QQ on cachelines in dirty shared state") with your Reported-by.
