### ISSUE TITLE
Error 127 is not a good error message 

### ISSUE THREAD

**Issue by Joilnen** [paulmckrcu/perfbook#6]
this happen when inkscape crashs, could you to change for a better expressive message ? 
advsync/irq.svg --> advsync/irq.pdf
make: *** [Makefile:467: advsync/irq.pdf] Error 127

**Comment by paulmckrcu** [comment]
On Sat, Sep 11, 2021 at 06:33:03AM -0700, Joilnen wrote:
> this happen when inkscape crashs, could you to change for a better expressive message ? 
> advsync/irq.svg --> advsync/irq.pdf
> make: *** [Makefile:467: advsync/irq.pdf] Error 127

What sort of improved error message are you looking for?  For example,
in your case, what error message would you have wanted to see?

Me, I haven't seen any inkscape crashes for quite some time.  In case
it helps, here is the version that I am using:

$ inkscape --version
Inkscape 0.92.5 (2060ec1f9f, 2020-04-08)

							Thanx, Paul

**Comment by akiyks** [comment]
@Joilnen  
Hi,
Building perfbook is being heavily tested on Ubuntu and Fedora.
On such systems, inkscape crashes very rarely. (Actually only once in 5 years or so
when inkscape 1.0.0 came out.)
Our use of inkscape causes a lot of warning messages to be emitted, so those
messages are gobbled (redirected to /dev/null) by default.

I pushed a branch to my fork of perfbook repository at:
https://github.com/akiyks/perfbook/tree/verbose-inkscape

Can you do a build there and let us know what the error message
from inkscape looks like?

Thanks, Akira

**Comment by Joilnen** [comment]
The inkscape crashes was my fault an outdated dependence, so it is not a perfbook compile problem, I just only got a lot of time to understand it because no messages about inkscape fail.
So to reproduce probably you only need to substitute a inkscape bin for a failed fake one, or take off some of it's dependence.
Thank you.
